# Generated by Django 4.0.3 on 2022-08-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='articles.categories'),
        ),
    ]
