# Generated by Django 4.0.3 on 2022-08-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='articles.categories', verbose_name='Название'),
        ),
    ]
