# Generated by Django 4.0.3 on 2022-08-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_scopedecision'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScopeDecision',
        ),
    ]
