# Generated by Django 4.0.3 on 2022-08-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_scopedecision'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScopeDecision',
        ),
    ]
