# Generated by Django 4.0.3 on 2022-08-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_delete_scopedecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='articles.article')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='articles.categories')),
            ],
        ),
    ]
