# Generated by Django 4.0.3 on 2022-08-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_scopedecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopedecision',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главная'),
        ),
    ]
