# Generated by Django 4.0.3 on 2022-08-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_scopedecision_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='is_main',
        ),
    ]
