# Generated by Django 4.0.3 on 2022-08-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_remove_categories_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главная'),
        ),
    ]
