# Generated by Django 4.0.3 on 2022-08-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_remove_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopedecision',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
