# Generated by Django 4.0.3 on 2022-08-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_scopedecision_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopedecision',
            options={'verbose_name': 'Тематики раздела', 'verbose_name_plural': 'Тематики раздела'},
        ),
    ]
