# Generated by Django 4.0.3 on 2022-08-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_alter_scopedecision_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopedecision',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='articles.article'),
        ),
    ]
