# Generated by Django 4.0.3 on 2022-08-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_alter_scopedecision_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScopeDecision',
        ),
    ]
