# Generated by Django 4.0.3 on 2022-08-10 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_delete_scopedecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='articles.article')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='articles.categories')),
            ],
            options={
                'verbose_name': 'Тематики раздела',
                'verbose_name_plural': 'Тематики раздела',
            },
        ),
    ]
