# Generated by Django 4.0.3 on 2022-08-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_scopedecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
