# Generated by Django 4.0.3 on 2022-08-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_remove_categories_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scopedecision',
            name='is_main',
        ),
    ]
