# Generated by Django 4.0.3 on 2022-08-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_scopedecision_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopedecision',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
