# Generated by Django 4.0.3 on 2022-08-09 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_subjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
