# Generated by Django 4.0.3 on 2022-08-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_delete_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to='school.teacher'),
        ),
    ]
