# Generated by Django 4.0.3 on 2022-08-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_student_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stud_Teach',
        ),
    ]
