# Generated by Django 4.0.3 on 2022-08-09 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_remove_student_teacher_student_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
