# Generated by Django 4.0.3 on 2022-08-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_rename_teachers_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(related_name='teachers', to='school.teacher'),
        ),
    ]
