# Generated by Django 4.0.3 on 2022-08-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
