# Generated by Django 4.0.3 on 2022-08-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_rename_teacher_student_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teachers',
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(related_name='teachers', to='school.teacher'),
        ),
    ]
