# Generated by Django 4.0.3 on 2022-08-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_remove_student_teachers_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
