# Generated by Django 4.0.3 on 2022-08-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='time',
            new_name='created_at',
        ),
    ]
