# Generated by Django 4.0.3 on 2022-08-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_sensor_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
