# Generated by Django 4.0.3 on 2022-08-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0008_alter_measurement_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='photo_url',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
