# Generated by Django 4.0.3 on 2022-08-02 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('price', models.CharField(blank=True, max_length=60)),
                ('image', models.ImageField(blank=True, upload_to='static/img')),
                ('release_date', models.DateField(default=datetime.date.today)),
                ('lte_exists', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
