# Generated by Django 4.0.3 on 2022-08-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='id_mod',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='phone',
            name='release_date',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
