# Generated by Django 4.0.3 on 2022-08-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='lte_exists2',
            field=models.BooleanField(default=False),
        ),
    ]
