# Generated by Django 4.0.3 on 2022-08-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phone_lte_exists2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='lte_exists2',
        ),
    ]
