# Generated by Django 4.0.3 on 2022-08-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phone_id_mod_phone_image_phone_lte_exists_phone_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='lte_exists',
        ),
    ]
