# Generated by Django 4.0.3 on 2022-08-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_remove_phone_lte_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='lte_exists',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
