# Generated by Django 4.0.3 on 2022-08-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_phone_lte_exists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='id_mod',
        ),
    ]
