# Generated by Django 4.0.3 on 2022-08-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_alter_phone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
